[package]
name = "serde-detach"
version = "0.0.0-dev"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.114"
wyz = "0.2.0"

[dev-dependencies]
serde = { version = "*", features = ["derive"] }
serde-any = { path = "../serde-any" }
taml = { path = "../taml", default-features = false }
